version: "3.9"
services:
  adapter:
    build: .
    image: gcr.io/tracer-external-adapters/dex
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - ETH_HTTP_URL=${ETH_HTTP_URL}
      - NAME=${NAME}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    restart: always